changed

diff --git a/.github/workflows/workflow_terraform_plan_apply.yml b/.github/workflows/workflow_terraform_plan_apply.yml
--- a/.github/workflows/workflow_terraform_plan_apply.yml
+++ b/.github/workflows/workflow_terraform_plan_apply.yml
@@ -161,20 +161,32 @@ jobs:
 
     - name: Terraform show
       run: terraform show -no-color $tfplanPath >> $tfplanTextPath
-
+    
     - name: Compare plan files
-      shell: pwsh
       run: |
         # Compare the plan text file (from this stage) with the artifact plan text file (from the plan stage).
         # Continue if both plan text files are the same.
         # Throw an error if there's a difference, indicating there has been a change in Azure since the plan was created.
-        fc.exe $tfplanTextPath ${{ runner.workspace }}/$tfplanTextArtifactName/$tfplanArtifactName.txt
+        cmp $tfplanTextPath ${{ runner.workspace }}/$tfplanTextArtifactName/$tfplanArtifactName.txt
+        if [ $? -eq 1 ]; then
+            echo "##[error]Terraform plan is out-of-date. The Azure resources involved in the plan have been modified since the plan was generated. Run this workflow again to generate a new Terraform plan."
+        else
+            echo "Files are identical."
+        fi
 
-        # Use fc.exe exit code, which will be True if the files are the same
-        if (-Not ($?)) {
-          Write-Output "##[error]Terraform plan is out-of-date. The Azure resources involved in the plan have been modified since the plan was generated. Run this workflow again to generate a new Terraform plan."
-            exit 1
-        }
+    # - name: Compare plan files
+    #   shell: pwsh
+    #   run: |
+    #     # Compare the plan text file (from this stage) with the artifact plan text file (from the plan stage).
+    #     # Continue if both plan text files are the same.
+    #     # Throw an error if there's a difference, indicating there has been a change in Azure since the plan was created.
+    #     fc.exe $tfplanTextPath ${{ runner.workspace }}/$tfplanTextArtifactName/$tfplanArtifactName.txt
+
+    #     # Use fc.exe exit code, which will be True if the files are the same
+    #     if (-Not ($?)) {
+    #       Write-Output "##[error]Terraform plan is out-of-date. The Azure resources involved in the plan have been modified since the plan was generated. Run this workflow again to generate a new Terraform plan."
+    #         exit 1
+    #     }
 
     # - name: Terraform Apply
     #   run: terraform apply -auto-approve -input=false
